language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
env:
    global:
        - XDEBUG_MODE=coverage
install:
    - composer self-update
    - composer update
    - composer --prefer-source install
script: ./vendor/bin/phpunit --coverage-text
cache:
  directories:
    - $HOME/.composer/cache
